#!/bin/sh

# SurfOS kiosk startup – fuldskærm med faner mulige
unclutter -idle 0.1 -root &  # Skjul mus

# Start Chromium i fuldskærm/app-mode (faner + indstillinger tilgængelige)
chromium-browser \
  --start-fullscreen \
  --app=https://www.startpage.com \
  --incognito \
  --no-first-run \
  --no-default-browser-check \
  --disable-features=TranslateUI \
  --disable-breakpad
